### PR TITLE
React capstone project - Metrics webapp

### PR DESCRIPTION
**Pull request by jlcarrascof**
### Features

- [ ] Dependencies and libraries installed.
- [ ] Components folder with air pollution items and a detailed (list) of every item.
- [ ] Fetch data from https://openweathermap.org/api/air-pollution
- [ ] File countries items and a list of these items for the home page
- [ ] Europe countries for the API of air pollution parameters
- [ ] Navbar for the navigation bar of the web app using router
- [ ] Search bar on the home page to filter country
- [ ] Back button function in the navbar to return to the home page
- [ ] Detail button in each country to see the air pollution data of that country (Only available in the arrow button, not the entire section).
- [ ] Redux store and DetailSlice for API fetch and search reducers.
- [ ] Jest tests for CountriesItems
- [ ] Graph bar for the values of air in the country details section.
- [ ] Fix Linters
- [ ] Update readme info and deploy and record video.

### CODE REVIEW

**Review by skyv26 — COMMENTED** [review]
## Hi @jlcarrascof, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🟨 



## Reason 🗒️ 
You have submitted a project, that has the wrong `Gitflow`. You should open a new PR with take all changes from the dev and should be mergeable into the main like `main <-- dev`. Kindly re-submit your project again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   @skyv26
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   linkedin-skyv2022
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   @vrma_aakash
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   @skybrel
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   @skybrel
</a>

</td>
</tr>
</table>

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jlcarrascof** [comment]
Excuse me, Mr Verma **@skyv26** 

You marked my pull request as invalid because the Git Flow.

I can't understand what I did wrong

I opened this last branch **"final-branch"** only for update the **Readme File with my recorded video and do the pull request**.

As you can see, after the approve ... this branch will join to dev and dev to main, respecting the Git Flow concept.

What am I doing bad, buddy?

**Comment by jlcarrascof** [comment]
Sorry, sir **@skyv26** 

You gave me the feedback and it was clear .... yes ....

"Reason 🗒️

You have submitted a project, that has the wrong Gitflow. You should open a new PR with take all changes from the dev and should be mergeable into the main like main <-- dev. Kindly re-submit your project again."

I will fix this issue.

My apologies, dear reviewer.

Javier.-

**Comment by jlcarrascof** [comment]
This is my new link, dear reviewer **@skyv26** 

https://github.com/jlcarrascof/React-capstone-project-Metrics-webapp/pull/7

If you have my project, Sir.

My apologies, again ... 

Javier.-

**Comment by iambenkis** [comment]
Hi @jlcarrascof  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

- [ ] You have submitted a project that is merged , make sure you to open a new PR and then ask  for a review


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@iambenkis` in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
